openapi: 3.0.0
info:
  title: Challenge1 API
  version: 1.0.0
paths:
  /dev/seed:
    post:
      summary: Seed deterministic data
      parameters:
        - in: query
          name: users
          schema: { type: integer }
        - in: query
          name: orders
          schema: { type: integer }
        - in: query
          name: products
          schema: { type: integer }
        - in: query
          name: seed
          schema: { type: integer }
      responses:
        '200':
          description: seeded
  /api/users:
    get:
      summary: Get users with aggregates
      parameters:
        - in: query
          name: page
          schema: { type: integer }
        - in: query
          name: pageSize
          schema: { type: integer }
        - in: query
          name: search
          schema: { type: string }
        - in: query
          name: sortBy
          schema: { type: string }
        - in: query
          name: sortDir
          schema: { type: string }
      responses:
        '200':
          description: OK
  /api/users/{id}/orders:
    get:
      summary: Get orders for user
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
